version: "3.9"

x-common-variables: &common-variables
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: shimshon
  MYSQL_HOST_IP: localhost
  REACT_APP_SERVER_PORT: 3001

services:
  mysql:
    image: mysql:8.0.0
    restart: unless-stopped
    environment:
      <<: *common-variables
      MYSQL_HOST: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      <<: *common-variables
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
  server:
    build: ./server
    depends_on:
      - mysql
    expose:
      - 3001
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
    links:
      - mysql
    command: npm run devStart
  client:
    build: ./client
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start
